import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (typeof window === 'undefined') {
    // Server render
    // eslint-disable-next-line no-console
    console.log('[RootLayout] Rendered on SERVER');
  } else {
    // Client render
    // eslint-disable-next-line no-console
    console.log('[RootLayout] Rendered on CLIENT');
  }
  return (
    <html lang="en">
      <body
        className={"antialiased"}
      >
        {children}
      </body>
    </html>
  );
}
