import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Development-only logging
  if (process.env.NODE_ENV === 'development') {
    console.log(`[RootLayout] Rendered on ${typeof window === 'undefined' ? 'SERVER' : 'CLIENT'}`);
  }
  return (
    <html lang="en">
      <body suppressHydrationWarning className="antialiased relative">
        {children}
        <div id="modal-root" className="absolute inset-0 pointer-events-none">
          {/* Modal content will be rendered here */}
        </div>
      </body>
    </html>
  );
}
